version: '2'

services:
  db:
    image: mariadb:10.6
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    restart: always
    networks:
      - nextcloud-internal
    volumes:
      - db:/var/lib/mysql
    environment:
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - stack.env

  redis:
    image: redis:alpine
    restart: always
    networks:
      - nextcloud-internal

  nextcloud:
    image: nextcloud:apache
    restart: always
    networks:
      - nextcloud-internal
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    nextcloud:
      - stack.env

volumes:
  db:
  nextcloud:


networks:
  nextcloud-internal:
